// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egmqcpvgdiwhxfomhjsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnbXFjcHZnZGl3aHhmb21oanNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzYyNjIsImV4cCI6MjA2NTkxMjI2Mn0.l4wbdd8-MEYDBboBIG5dZRXo6tsVVK1YzV4nyeftg1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});